services:
  ssht:
    build: ..
    ports:
      - "6001:6001"
    volumes:
      - ./ssh-keys:/root/.ssh:ro
      - ./config:/root/.config/ssht
    depends_on:
      - ssh-server
    networks:
      - test-net

  echo-server:
    image: ealen/echo-server:latest
    networks:
      - test-net

  ssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      - PUID=1000
      - PGID=1000
      - PASSWORD_ACCESS=false
      - USER_NAME=testuser
      - DOCKER_MODS=linuxserver/mods:openssh-server-ssh-tunnel
    volumes:
      - ./ssh-keys/id_rsa.pub:/config/.ssh/authorized_keys:ro
    networks:
      - test-net

networks:
  test-net:
    driver: bridge
